// AUTO-GENERATED by generate-catalog.py — do not edit by hand.
// Re-run the script after adding/removing images in art/.
const CATALOG = {
  "Original": [
    "art/Original/2026-07-25_0000 key-art-clean.png"
  ]
};
