// AUTO-GENERATED by generate-catalog.py — do not edit by hand.
// Re-run the script after adding/removing images in art/.
const CATALOG = {
  "Current - Main Capsule": [
    "art/Current - Main Capsule/Steam - Main Capsule.png"
  ],
  "Current - Small Capsule": [
    "art/Current - Small Capsule/Steam - Small Capsule.png"
  ],
  "Orange - Main Capsule": [
    "art/Orange - Main Capsule/Screenshot 2026-07-27 at 18.17.37 (x2).png",
    "art/Orange - Main Capsule/Screenshot 2026-07-27 at 18.18.29 (x2).png",
    "art/Orange - Main Capsule/Screenshot 2026-07-27 at 18.20.34 (x2).png"
  ],
  "Orange - Small Capsule": [
    "art/Orange - Small Capsule/Screenshot 2026-07-28 at 12.50.26.png",
    "art/Orange - Small Capsule/Screenshot 2026-07-28 at 12.54.27.png",
    "art/Orange - Small Capsule/Screenshot 2026-07-29 at 15.50.36.png"
  ],
  "Orange - Vertical Capsule": [
    "art/Orange - Vertical Capsule/Screenshot 2026-07-31 at 10.19.31.png",
    "art/Orange - Vertical Capsule/Screenshot 2026-07-31 at 10.38.27.png",
    "art/Orange - Vertical Capsule/Screenshot 2026-07-31 at 10.51.04.png",
    "art/Orange - Vertical Capsule/Screenshot 2026-07-31 at 14.51.15.png"
  ],
  "Red - Main Capsule": [
    "art/Red - Main Capsule/Screenshot 2026-07-25 at 12.30.22 (x2).png",
    "art/Red - Main Capsule/Screenshot 2026-07-26 at 15.05.37.png",
    "art/Red - Main Capsule/Screenshot 2026-07-26 at 15.25.58 (x2).png",
    "art/Red - Main Capsule/Screenshot 2026-07-26 at 15.36.49 (x2).png",
    "art/Red - Main Capsule/Screenshot 2026-07-26 at 15.44.12 (x2).png",
    "art/Red - Main Capsule/Screenshot 2026-07-26 at 15.46.31 (x2).png"
  ],
  "Red - Small Capsule": [
    "art/Red - Small Capsule/Screenshot 2026-07-26 at 16.00.58 (x2).png",
    "art/Red - Small Capsule/Screenshot 2026-07-26 at 16.07.07 (x2).png"
  ],
  "Turquoise - Main Capsule": [
    "art/Turquoise - Main Capsule/Screenshot 2026-07-25 at 12.29.42 (x2).png",
    "art/Turquoise - Main Capsule/Screenshot 2026-07-26 at 14.19.30 (x2).png"
  ],
  "Turquoise - Small Capsule": [
    "art/Turquoise - Small Capsule/Screenshot 2026-07-26 at 14.35.42.png",
    "art/Turquoise - Small Capsule/Screenshot 2026-07-26 at 14.42.00 (x2).png"
  ]
};
