#!/usr/bin/env python3
"""Enumerate key art branches into catalog-data.js.

Drop images into art/<BranchName>/ — one subfolder per design branch
(e.g. art/Red/, art/Turquoise/, art/Vertical/). Files are sorted by
filename, so date+time prefixed names order themselves into v01, v02, ...

Run this script (no args), then commit. The viewer reads catalog-data.js.
"""

import json
from pathlib import Path

HERE = Path(__file__).resolve().parent
ART_DIR = HERE / "art"
OUT_FILE = HERE / "catalog-data.js"
IMAGE_EXTS = {".png", ".jpg", ".jpeg", ".webp", ".gif"}


def main():
    catalog = {}
    for branch_dir in sorted(ART_DIR.iterdir()):
        if not branch_dir.is_dir() or branch_dir.name.startswith("."):
            continue
        files = sorted(
            f.name
            for f in branch_dir.iterdir()
            if f.is_file() and f.suffix.lower() in IMAGE_EXTS
        )
        if files:
            catalog[branch_dir.name] = [f"art/{branch_dir.name}/{f}" for f in files]

    js = (
        "// AUTO-GENERATED by generate-catalog.py — do not edit by hand.\n"
        "// Re-run the script after adding/removing images in art/.\n"
        f"const CATALOG = {json.dumps(catalog, indent=2)};\n"
    )
    OUT_FILE.write_text(js)

    total = sum(len(v) for v in catalog.values())
    print(f"Wrote {OUT_FILE.name}: {len(catalog)} branch(es), {total} image(s)")
    for branch, files in catalog.items():
        print(f"  {branch}: {len(files)} version(s)")
        for i, f in enumerate(files):
            print(f"    v{i + 1:02d}  {Path(f).name}")


if __name__ == "__main__":
    main()
