#!/usr/bin/env python3
"""Snapshot Steam's homepage "New Releases" tab into store-list-data.js.

Used by the LIST view (homepage-tab-style rows: capsule, title, tags,
release date, price). Re-run whenever the lineup should be refreshed,
then commit the regenerated file.

Usage: python3 update-store-list.py [row-count]   (default 14)
"""

import html as html_mod
import json
import re
import sys
import urllib.request
from pathlib import Path

HERE = Path(__file__).resolve().parent
OUT_FILE = HERE / "store-list-data.js"
FEATURED_URL = "https://store.steampowered.com/api/featuredcategories?cc=nl&l=english"
DETAILS_URL = "https://store.steampowered.com/api/appdetails?appids={}&cc=nl&l=english"
APP_URL = "https://store.steampowered.com/app/{}/"
UA = {"User-Agent": "Mozilla/5.0",
      "Cookie": "birthtime=568022401; lastagecheckage=1-January-1988; wants_mature_content=1"}
MAX_TAGS = 4


def fetch(url):
    return urllib.request.urlopen(urllib.request.Request(url, headers=UA)).read().decode("utf-8")


def enrich(appid):
    """Pull release date + price from appdetails, tags + review from the app page."""
    out = {"released": "", "price": "", "originalPrice": "", "discount": "",
           "tags": [], "review": None}
    try:
        d = json.loads(fetch(DETAILS_URL.format(appid)))[str(appid)]["data"]
        out["released"] = d.get("release_date", {}).get("date", "")
        if d.get("is_free"):
            out["price"] = "Free"
        elif "price_overview" in d:
            po = d["price_overview"]
            out["price"] = po.get("final_formatted", "")
            if po.get("discount_percent"):
                out["discount"] = f"-{po['discount_percent']}%"
                out["originalPrice"] = po.get("initial_formatted", "")
    except Exception as e:
        print(f"    (appdetails failed for {appid}: {e})")
    try:
        page = fetch(APP_URL.format(appid))
        out["tags"] = [html_mod.unescape(t.strip()) for t in
                       re.findall(r'class="app_tag"[^>]*>\s*(.*?)\s*</a>', page)][:MAX_TAGS]
        m = re.search(r'class="game_review_summary (\w+)"[^>]*>([^<]+)<', page)
        if m and "not_enough_reviews" not in m.group(1):
            out["review"] = {"tone": m.group(1), "summary": m.group(2).strip()}
    except Exception as e:
        print(f"    (app page failed for {appid}: {e})")
    return out


def main():
    count = int(sys.argv[1]) if len(sys.argv) > 1 else 14
    items = json.loads(fetch(FEATURED_URL))["new_releases"]["items"]

    games, seen = [], set()
    for it in items:
        if it["id"] in seen or not it.get("small_capsule_image"):
            continue
        seen.add(it["id"])
        print(f"  fetching {it['name']} ({it['id']})")
        game = {
            "appid": it["id"],
            "name": html_mod.unescape(it["name"]),
            "img": it["small_capsule_image"].split("?")[0],
            **enrich(it["id"]),
        }
        games.append(game)
        if len(games) >= count:
            break

    js = (
        "// AUTO-GENERATED by update-store-list.py — do not edit by hand.\n"
        "// Steam homepage 'New Releases' snapshot. Re-run the script to refresh.\n"
        f"const STORE_LIST = {json.dumps(games, indent=2, ensure_ascii=False)};\n"
    )
    OUT_FILE.write_text(js)
    print(f"Wrote {OUT_FILE.name}: {len(games)} games")
    for g in games:
        rev = g["review"]["summary"] if g["review"] else "no reviews"
        print(f"  {g['name']}  [{g['price'] or '—'}]  {g['released']}  ({rev})  {', '.join(g['tags'])}")


if __name__ == "__main__":
    main()
