#!/usr/bin/env python3
"""Snapshot the Steam homepage "Popular New Releases" tab into store-list-data.js.

Parses the actual server-rendered homepage tab (the curated list visitors see),
so rows come with title, tags, release date, price/discount and the 231x87@2x
capsule. Re-run whenever the lineup should be refreshed, then commit.

Usage: python3 update-store-list.py [row-count]   (default 14)
"""

import html as html_mod
import json
import re
import sys
import urllib.request
from pathlib import Path

HERE = Path(__file__).resolve().parent
OUT_FILE = HERE / "store-list-data.js"
HOME_URL = "https://store.steampowered.com/?cc=nl&l=english"
UA = {"User-Agent": "Mozilla/5.0", "Cookie": "birthtime=568022401"}


def text_of(pattern, blob, default=""):
    m = re.search(pattern, blob, re.S)
    return html_mod.unescape(re.sub(r"\s+", " ", m.group(1)).strip()) if m else default


def main():
    count = int(sys.argv[1]) if len(sys.argv) > 1 else 14
    page = urllib.request.urlopen(
        urllib.request.Request(HOME_URL, headers=UA)).read().decode("utf-8")

    # only the Popular New Releases tab section
    start = page.find('tab_newreleases_content"')
    end = page.find('tab_topsellers_content"', start)
    section = page[start:end]

    games = []
    chunks = re.split(r'<a href="https://store\.steampowered\.com/app/(\d+)[^"]*"\s+class="tab_row_item"', section)
    for appid, row in zip(chunks[1::2], chunks[2::2]):
        game = {
            "appid": int(appid),
            "name": text_of(r'class="tab_item_title">(.*?)</div>', row),
            "img": text_of(r'data-delayed-image="([^"?]+capsule_231x87[^"?]*)', row),
            "released": text_of(r'class="tab_item_release_date">(?:Released:)?\s*(.*?)</div>', row),
            "tags": [t.lstrip(", ") for t in re.findall(r'<span class="top_tag">(.*?)</span>', row)],
            "price": text_of(r'class="discount_final_price">(.*?)</div>', row),
            "originalPrice": text_of(r'class="discount_original_price">(.*?)</div>', row),
            "discount": text_of(r'class="discount_pct">(.*?)</div>', row),
        }
        if not (game["name"] and game["img"]):
            continue
        games.append(game)
        if len(games) >= count:
            break

    js = (
        "// AUTO-GENERATED by update-store-list.py — do not edit by hand.\n"
        "// Steam homepage 'Popular New Releases' snapshot. Re-run the script to refresh.\n"
        f"const STORE_LIST = {json.dumps(games, indent=2, ensure_ascii=False)};\n"
    )
    OUT_FILE.write_text(js)
    print(f"Wrote {OUT_FILE.name}: {len(games)} games")
    for g in games:
        price = f"{g['discount']} {g['originalPrice']} -> {g['price']}" if g["discount"] else g["price"]
        print(f"  {g['name']}  [{price or '—'}]  {g['released']}  {', '.join(g['tags'])}")


if __name__ == "__main__":
    main()
