/* Garbage Country key art viewer.
 * Reads CATALOG from catalog-data.js (generated by generate-catalog.py).
 * URL params: ?b=<branch>&v=<num>&view=full|store  e.g. ?b=Red&v=3&view=store
 */

// Neighbor games shown around our key art in the store preview.
// Capsules are pulled live from the Steam CDN by app id. Newer Steam apps
// use hashed asset URLs — for those, set an explicit `img` override
// (grab it from the store page: the big header image URL).
const NEIGHBORS = [
    { appid: 1458140, name: "Pacific Drive",
      img: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1458140/3a5fa1e845c13b48f9e2ed042f4538ac62bd16ed/header.jpg" },
    { appid: 1562430, name: "DREDGE" },
    { appid: 2929250, name: "over the hill" },
    { appid: 2997230, name: "Planet of Lana II",
      img: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/2997230/7712fdf6cd6531709c16920f8b20b6ee146ac9f8/header.jpg" },
    { appid: 757310,  name: "Sable" },
    { appid: 4162340, name: "Verdant",
      img: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/4162340/ea7e75f685b5ca4c242b1a14c583354b24c384b9/header.jpg" },
    { appid: 3293010, name: "Easy Delivery Co.",
      img: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/3293010/2d0ded07083fd997234193517d5a6c65a1cf7920/header.jpg" },
    { appid: 4005880, name: "DETOUR",
      img: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/4005880/f144126f46c762be8890a21ca61cc74118f85b14/header.jpg" },
    { appid: 3090810, name: "Truckful",
      img: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/3090810/84527335c4107d4ad2e459e97f0af3b0343ffbc2/header.jpg" },
];
const OUR_NAME = "Garbage Country";

const capsuleUrl = (appid) =>
    `https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/${appid}/header.jpg`;

// ---------- state ----------
const branches = Object.keys(CATALOG);
let branch = branches[0] || null;
let version = 0;           // 0-based index into CATALOG[branch]
let view = "full";         // "full" | "store"
let gridOrder = null;      // shuffled neighbor order + our slot, kept until reshuffle

// ---------- els ----------
const $ = (id) => document.getElementById(id);
const els = {
    dropdown: $("branch-dropdown"), branchBtn: $("branch-btn"),
    branchLabel: $("branch-label"), branchMenu: $("branch-menu"),
    pips: $("pips"), prev: $("prev-btn"), next: $("next-btn"),
    btnFull: $("btn-full"), btnStore: $("btn-store"), shuffle: $("shuffle-btn"),
    fullView: $("full-view"), storeView: $("store-view"),
    fullImg: $("full-img"), fullCaption: $("full-caption"),
    grid: $("grid"), empty: $("empty-state"),
};

const vLabel = (i) => "v" + String(i + 1).padStart(2, "0");
const files = () => (branch ? CATALOG[branch] : []);
const currentFile = () => files()[version];

// ---------- url sync ----------
function readUrl() {
    const p = new URLSearchParams(location.search);
    const b = p.get("b");
    if (b && CATALOG[b]) branch = b;
    version = files().length - 1; // default to latest
    const v = parseInt(p.get("v"), 10);
    if (v >= 1 && v <= files().length) version = v - 1;
    if (p.get("view") === "store") view = "store";
}

function writeUrl() {
    const p = new URLSearchParams();
    p.set("b", branch);
    p.set("v", version + 1);
    if (view === "store") p.set("view", "store");
    history.replaceState(null, "", "?" + p.toString());
}

// ---------- render ----------
function render() {
    writeUrl();
    document.title = `${OUR_NAME} — ${branch} ${vLabel(version)}`;

    // branch dropdown
    els.branchLabel.textContent = branch;
    els.branchMenu.innerHTML = "";
    for (const b of branches) {
        const item = document.createElement("div");
        item.className = "dropdown-item" + (b === branch ? " active" : "");
        item.setAttribute("role", "option");
        item.innerHTML = `<span>${b}</span><span class="count">${CATALOG[b].length} version${CATALOG[b].length > 1 ? "s" : ""}</span>`;
        item.addEventListener("click", () => {
            branch = b;
            version = files().length - 1;
            els.dropdown.classList.remove("open");
            render();
        });
        els.branchMenu.appendChild(item);
    }

    // version pips
    els.pips.innerHTML = "";
    files().forEach((_, i) => {
        const pip = document.createElement("button");
        pip.className = "ver-pip" + (i === version ? " active" : "");
        pip.textContent = vLabel(i);
        pip.addEventListener("click", () => { version = i; render(); });
        els.pips.appendChild(pip);
    });
    els.prev.disabled = version <= 0;
    els.next.disabled = version >= files().length - 1;

    // view toggle
    els.btnFull.classList.toggle("active", view === "full");
    els.btnStore.classList.toggle("active", view === "store");
    els.fullView.style.display = view === "full" ? "flex" : "none";
    els.storeView.style.display = view === "store" ? "block" : "none";
    els.shuffle.style.display = view === "store" ? "flex" : "none";

    if (view === "full") renderFull();
    else renderStore();
}

function renderFull() {
    const f = currentFile();
    els.fullImg.src = encodeURI(f);
    els.fullImg.onload = () => {
        els.fullCaption.textContent =
            `${branch} ${vLabel(version)} — ${f.split("/").pop()} — ` +
            `${els.fullImg.naturalWidth}×${els.fullImg.naturalHeight}`;
    };
    els.fullCaption.textContent = `${branch} ${vLabel(version)} — ${f.split("/").pop()}`;
}

function shuffleGrid() {
    const order = NEIGHBORS.slice();
    for (let i = order.length - 1; i > 0; i--) {
        const j = Math.floor(Math.random() * (i + 1));
        [order[i], order[j]] = [order[j], order[i]];
    }
    // drop ours somewhere in the middle of the pack, never dead first or last
    const slot = 1 + Math.floor(Math.random() * (order.length - 1));
    order.splice(slot, 0, { ours: true });
    gridOrder = order;
}

function renderStore() {
    if (!gridOrder) shuffleGrid();
    els.grid.innerHTML = "";
    for (const entry of gridOrder) {
        const cap = document.createElement("a");
        cap.className = "capsule";
        const wrap = document.createElement("div");
        wrap.className = "img-wrap";
        const img = document.createElement("img");
        img.loading = "lazy";
        const title = document.createElement("div");
        title.className = "title";
        if (entry.ours) {
            img.src = encodeURI(currentFile());
            img.alt = OUR_NAME;
            title.textContent = OUR_NAME;
        } else {
            img.src = entry.img || capsuleUrl(entry.appid);
            img.alt = entry.name;
            title.textContent = entry.name;
            cap.href = `https://store.steampowered.com/app/${entry.appid}/`;
            cap.target = "_blank";
            cap.rel = "noopener";
        }
        wrap.appendChild(img);
        cap.appendChild(wrap);
        cap.appendChild(title);
        els.grid.appendChild(cap);
    }
}

// ---------- events ----------
els.branchBtn.addEventListener("click", (e) => {
    e.stopPropagation();
    els.dropdown.classList.toggle("open");
});
document.addEventListener("click", () => els.dropdown.classList.remove("open"));

els.prev.addEventListener("click", () => { if (version > 0) { version--; render(); } });
els.next.addEventListener("click", () => { if (version < files().length - 1) { version++; render(); } });
els.btnFull.addEventListener("click", () => { view = "full"; render(); });
els.btnStore.addEventListener("click", () => { view = "store"; render(); });
els.shuffle.addEventListener("click", () => { shuffleGrid(); renderStore(); });

document.addEventListener("keydown", (e) => {
    if (e.key === "ArrowLeft" && version > 0) { version--; render(); }
    else if (e.key === "ArrowRight" && version < files().length - 1) { version++; render(); }
    else if (e.key === "f") { view = "full"; render(); }
    else if (e.key === "s") { view = "store"; render(); }
});

// ---------- init ----------
if (!branch) {
    els.empty.style.display = "block";
    document.querySelector("header .nav-group").style.visibility = "hidden";
    document.querySelector("header .right-group").style.visibility = "hidden";
} else {
    readUrl();
    render();
}
