/* Garbage Country key art viewer.
 * Reads CATALOG from catalog-data.js (generated by generate-catalog.py).
 * URL params: ?b=<branch>&v=<num>&view=full|store  e.g. ?b=Red&v=3&view=store
 */

// Neighbor games shown around our key art in the store preview.
// MAIN capsules (616×353) pulled live from the Steam CDN — most apps use
// hashed asset URLs, so each entry pins the exact `img` its store page
// currently serves (re-grab from the store page if one goes stale).
const NEIGHBORS = [
    { appid: 1458140, name: "Pacific Drive",
      img: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1458140/2760a8bda00bf838d5295e9c7e2ad9f64d106e23/capsule_616x353.jpg" },
    { appid: 1562430, name: "DREDGE" },
    { appid: 2929250, name: "over the hill",
      img: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/2929250/c9074a798026361d9c8521ef9a23d6e52c0bea38/capsule_616x353.jpg" },
    { appid: 2997230, name: "Planet of Lana II",
      img: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/2997230/1d4097479477a29de0b6672df90fbbe86aeeaefc/capsule_616x353.jpg" },
    { appid: 757310,  name: "Sable" },
    { appid: 4162340, name: "Verdant",
      img: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/4162340/4d414f2cd0f872116778c5ee787f0d9034fffe84/capsule_616x353.jpg" },
    { appid: 3293010, name: "Easy Delivery Co.",
      img: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/3293010/d6c4ab7b057ebf4af98f8ebc5a713590e9da95fa/capsule_616x353.jpg" },
    { appid: 4005880, name: "DETOUR",
      img: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/4005880/4b7e56ccc18b4a93acfe0fdcf42221ea9761014a/capsule_616x353.jpg" },
    { appid: 3090810, name: "Truckful",
      img: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/3090810/689f586d9d6c5fd442426721d553cd062f0b44d1/capsule_616x353.jpg" },
];
const OUR_NAME = "Garbage Country";

// Our row in the LIST view (new-releases style). Tweak freely.
const OUR_ROW = {
    tags: ["Open World", "Exploration", "Driving", "Atmospheric"],
    released: "25 Jul, 2026",
    price: "9,75€",
};

const capsuleUrl = (appid) =>
    `https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/${appid}/capsule_616x353.jpg`;

// ---------- state ----------
const branches = Object.keys(CATALOG);
let branch = branches[0] || null;
let version = 0;           // 0-based index into CATALOG[branch]
let view = "full";         // "full" | "store" | "list"
let gridOrder = null;      // shuffled neighbor order + our slot, kept until reshuffle
let listSlot = null;       // index of our row in the list view

// ---------- els ----------
const $ = (id) => document.getElementById(id);
const els = {
    dropdown: $("branch-dropdown"), branchBtn: $("branch-btn"),
    branchLabel: $("branch-label"), branchMenu: $("branch-menu"),
    pips: $("pips"), prev: $("prev-btn"), next: $("next-btn"),
    btnFull: $("btn-full"), btnStore: $("btn-store"), btnList: $("btn-list"),
    shuffle: $("shuffle-btn"),
    fullView: $("full-view"), storeView: $("store-view"), listView: $("list-view"),
    fullImg: $("full-img"), fullCaption: $("full-caption"),
    grid: $("grid"), rows: $("rows"), empty: $("empty-state"),
};

const vLabel = (i) => "v" + String(i + 1).padStart(2, "0");
const files = () => (branch ? CATALOG[branch] : []);
const currentFile = () => files()[version];

// ---------- url sync ----------
function readUrl() {
    const p = new URLSearchParams(location.search);
    const b = p.get("b");
    if (b && CATALOG[b]) branch = b;
    version = files().length - 1; // default to latest
    const v = parseInt(p.get("v"), 10);
    if (v >= 1 && v <= files().length) version = v - 1;
    if (["store", "list"].includes(p.get("view"))) view = p.get("view");
}

function writeUrl() {
    const p = new URLSearchParams();
    p.set("b", branch);
    p.set("v", version + 1);
    if (view !== "full") p.set("view", view);
    history.replaceState(null, "", "?" + p.toString());
}

// ---------- render ----------
function render() {
    writeUrl();
    document.title = `${OUR_NAME} — ${branch} ${vLabel(version)}`;

    // branch dropdown
    els.branchLabel.textContent = branch;
    els.branchMenu.innerHTML = "";
    for (const b of branches) {
        const item = document.createElement("div");
        item.className = "dropdown-item" + (b === branch ? " active" : "");
        item.setAttribute("role", "option");
        item.innerHTML = `<span>${b}</span><span class="count">${CATALOG[b].length} version${CATALOG[b].length > 1 ? "s" : ""}</span>`;
        item.addEventListener("click", () => {
            branch = b;
            version = files().length - 1;
            els.dropdown.classList.remove("open");
            render();
        });
        els.branchMenu.appendChild(item);
    }

    // version pips
    els.pips.innerHTML = "";
    files().forEach((_, i) => {
        const pip = document.createElement("button");
        pip.className = "ver-pip" + (i === version ? " active" : "");
        pip.textContent = vLabel(i);
        pip.addEventListener("click", () => { version = i; render(); });
        els.pips.appendChild(pip);
    });
    els.prev.disabled = version <= 0;
    els.next.disabled = version >= files().length - 1;

    // view toggle
    els.btnFull.classList.toggle("active", view === "full");
    els.btnStore.classList.toggle("active", view === "store");
    els.btnList.classList.toggle("active", view === "list");
    els.fullView.style.display = view === "full" ? "flex" : "none";
    els.storeView.style.display = view === "store" ? "block" : "none";
    els.listView.style.display = view === "list" ? "block" : "none";
    els.shuffle.style.display = view === "full" ? "none" : "flex";

    if (view === "full") renderFull();
    else if (view === "store") renderStore();
    else renderList();
}

function renderFull() {
    const f = currentFile();
    els.fullImg.src = encodeURI(f);
    els.fullImg.onload = () => {
        els.fullCaption.textContent =
            `${branch} ${vLabel(version)} — ${f.split("/").pop()} — ` +
            `${els.fullImg.naturalWidth}×${els.fullImg.naturalHeight}`;
    };
    els.fullCaption.textContent = `${branch} ${vLabel(version)} — ${f.split("/").pop()}`;
}

function shuffleGrid() {
    const order = NEIGHBORS.slice();
    for (let i = order.length - 1; i > 0; i--) {
        const j = Math.floor(Math.random() * (i + 1));
        [order[i], order[j]] = [order[j], order[i]];
    }
    // drop ours somewhere in the middle of the pack, never dead first or last
    const slot = 1 + Math.floor(Math.random() * (order.length - 1));
    order.splice(slot, 0, { ours: true });
    gridOrder = order;
}

function renderList() {
    if (listSlot === null) listSlot = 1 + Math.floor(Math.random() * (STORE_LIST.length - 1));
    els.rows.innerHTML = "";
    const entries = STORE_LIST.slice();
    entries.splice(listSlot, 0, { ours: true });
    for (const g of entries) {
        const row = document.createElement("a");
        row.className = "row";

        const cap = document.createElement("div");
        cap.className = "row-cap";
        const img = document.createElement("img");
        img.loading = "lazy";
        cap.appendChild(img);

        const mid = document.createElement("div");
        mid.className = "row-mid";
        const title = document.createElement("div");
        title.className = "row-title";
        const tags = document.createElement("div");
        tags.className = "row-tags";
        const released = document.createElement("div");
        released.className = "row-released";
        mid.appendChild(title);
        mid.appendChild(tags);
        mid.appendChild(released);

        const right = document.createElement("div");
        right.className = "row-right";
        const price = document.createElement("div");
        price.className = "row-price";
        right.appendChild(price);

        const d = g.ours
            ? { name: OUR_NAME, img: encodeURI(currentFile()), ...OUR_ROW }
            : g;
        img.src = d.img;
        img.alt = d.name;
        title.textContent = d.name;
        tags.textContent = (d.tags || []).join(", ");
        released.textContent = d.released ? `Released: ${d.released}` : "";
        const priceHtml = d.discount
            ? `<div class="disc">${d.discount}</div>` +
              `<div class="prices"><div class="orig">${d.originalPrice}</div>` +
              `<div class="final">${d.price}</div></div>`
            : `<div class="prices"><div class="final">${d.price || ""}</div></div>`;
        price.innerHTML = priceHtml;
        if (!g.ours) {
            row.href = `https://store.steampowered.com/app/${g.appid}/`;
            row.target = "_blank";
            row.rel = "noopener";
        }

        row.appendChild(cap);
        row.appendChild(mid);
        row.appendChild(right);
        els.rows.appendChild(row);
    }
}

function renderStore() {
    if (!gridOrder) shuffleGrid();
    els.grid.innerHTML = "";
    for (const entry of gridOrder) {
        const cap = document.createElement("a");
        cap.className = "capsule";
        const wrap = document.createElement("div");
        wrap.className = "img-wrap";
        const img = document.createElement("img");
        img.loading = "lazy";
        const title = document.createElement("div");
        title.className = "title";
        if (entry.ours) {
            img.src = encodeURI(currentFile());
            img.alt = OUR_NAME;
            title.textContent = OUR_NAME;
        } else {
            img.src = entry.img || capsuleUrl(entry.appid);
            img.alt = entry.name;
            title.textContent = entry.name;
            cap.href = `https://store.steampowered.com/app/${entry.appid}/`;
            cap.target = "_blank";
            cap.rel = "noopener";
        }
        wrap.appendChild(img);
        cap.appendChild(wrap);
        cap.appendChild(title);
        els.grid.appendChild(cap);
    }
}

// ---------- events ----------
els.branchBtn.addEventListener("click", (e) => {
    e.stopPropagation();
    els.dropdown.classList.toggle("open");
});
document.addEventListener("click", () => els.dropdown.classList.remove("open"));

els.prev.addEventListener("click", () => { if (version > 0) { version--; render(); } });
els.next.addEventListener("click", () => { if (version < files().length - 1) { version++; render(); } });
els.btnFull.addEventListener("click", () => { view = "full"; render(); });
els.btnStore.addEventListener("click", () => { view = "store"; render(); });
els.btnList.addEventListener("click", () => { view = "list"; render(); });
els.shuffle.addEventListener("click", () => {
    if (view === "store") { shuffleGrid(); renderStore(); }
    else if (view === "list") { listSlot = null; renderList(); }
});

document.addEventListener("keydown", (e) => {
    if (e.key === "ArrowLeft" && version > 0) { version--; render(); }
    else if (e.key === "ArrowRight" && version < files().length - 1) { version++; render(); }
    else if (e.key === "f") { view = "full"; render(); }
    else if (e.key === "s") { view = "store"; render(); }
    else if (e.key === "l") { view = "list"; render(); }
});

// ---------- init ----------
if (!branch) {
    els.empty.style.display = "block";
    document.querySelector("header .nav-group").style.visibility = "hidden";
    document.querySelector("header .right-group").style.visibility = "hidden";
} else {
    readUrl();
    render();
}
